global_defaults: &global_defaults
  image: ghcr.io/madeleinehj/scrapers:latest
  schedule: null          # manual only
  retries: 2
  retry_delay_minutes: 5

pipelines:
  - name: football
    <<: *global_defaults
    dbt_schedule: "0 6 * * *"
    dbt_selects:
      - bronze_layer.bronze_football
      - silver_layer.silver_football
    spiders:
      - football_standings
      - football_matches
      - football_top_scorers

  - name: transfermarkt
    <<: *global_defaults
    dbt_selects: []
    spiders:
      - transfermarkt_squads
      - transfermarkt_market_values
      - transfermarkt_transfers